kid1=["Which month of the year has the least number of days?",
      " Which is the world’s largest flower?",
      " How many bones does an adult human have?",
      "how many grams are there in 1kilogram?",
      "What color symbolizes peace?",
      "Which is the nearest star to planet earth?", 
      "Which is the largest ocean in the world?",
      "what is the name of nobita's mother?",
      "how many players are there in a cricket team?",
      "what of these channel telecast the shinchan show?",
      "Who invented the Computer?",
      " Which place is known as the roof of the world?",
      "Which is the smallest continent in the world?",
      " Who painted the Mona Lisa?",
      "Global warming is caused by the excess of which type of gas?"
      ]

options_A_kid1=["April",
            "Lotus",
            "206",
            "1000",
            "orange",
            "sun",
            "indian ocean",
            "Honekawa",
            "12",
            "pogo",
            "bill gates",
            "russia",
            "australia",
            "mary casset",
            "nitrogen"]
options_B_kid1=["Feburary",
            "Sunflower",
            "217",
            "2000",
            "pink","jupiter",
            "pacific ocean",
            "tamako nobi",
            "20",
            "cartoon network",
            "Charles Babbage",
            "tibet",
            "africa",
            "Giotto di Bondone ",
            "sulphur dioxide"]
options_C_kid1=["march",
            "Rafflesia",
            "309",
            "1001",
            "green",
            "pluto",
            "nile",
            "Dorami",
            "11",
            "nick",
            "neil armstrong",
            "India",
            "asia",
            "Pablo Picasso",
            "chlorine"
            ]
options_D_kid1=["October",
            "tulip",
            "409"
            "3000",
            "white",
            "moon",
            "atlantic ocean",
            "suzuka",
            "10",
            "hungama",
            "Thomas Edison",
            "China",
            "north america",
            "Leonardo da Vinci"
            "carbon dioxide"]
answers_kid1=["Feburary",
            "Rafflesia",
            "206",
            "1000",
            "white",
            "sun",
            "pacific ocean",
            "tamako nobi",
            "11",
            "hungama",
            "Charles Babbage",
            "tibet",
            "australia",
            "Leonardo da Vinci",
            "carbon dioxide"
            ]

kidquest=[kid1]
totalAkid=[options_A_kid1]
totalBkid=[options_B_kid1]
totalCkid=[options_C_kid1]
totalDkid=[options_D_kid1]